version: '3'
services:

  worker:
    image: mariosky/worker
    volumes:
      - /code
    command: python main.py
    environment:
      PYTHONUNBUFFERED: 1
      REDIS_HOST: 54.149.107.2
    logging:
      driver: awslogs
      options: 
        awslogs-region: us-west-2
        awslogs-group: docker-logs
        awslogs-stream-prefix: worker

