FROM docker.elastic.co/elasticsearch/elasticsearch:7.1.1
#COPY --chown=elasticsearch:elasticsearch elasticsearch.yml /usr/share/elasticsearch/config/
#RUN  chmod 664 -R  /usr/share/elasticsearch/data/



